version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:8080
  backend:
    image: backend
    build:
      context: ./server
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000