version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/var/www
      - ./cert:/etc/nginx/cert
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf  # Volume for Nginx configuration
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
