version: '3.4'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000