version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/custom:/etc/nginx/cert
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf  # Volume for Nginx configuration
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
    command: sh -c "npx prisma generate && npm start"
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
