version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:8080
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000